### PR TITLE
Add Docker image

### PR DESCRIPTION
**Pull request by claabs**
Adds Dockerfile and instructions on how to use the image. I managed to get the image to be a tiny 3.81 MB.

~~Due to the project structure and limitations with Docker volume defaults (empty volume creates a directory rather than file), the user must create the config.txt in advance.~~

I recommend creating a Docker Hub page alongside the repo if you merge this in. I already used `sevenchords/cipesathome` as the location in the Readme. You'll have to update it if you decide to change the name. Here's the Docker hub listing for my fork of the project: https://hub.docker.com/r/charlocharlie/cipesathome

Here's the Docker Hub build config I recommend (pretty much all defaults):
image

### CODE REVIEW

**Comment by claabs** [comment]
Switch to draft as I draw up a better config management solution (default config, environment variables).

**Comment by claabs** [comment]
Updated the configuration approach to automatically create a `config.txt` and accept environment variables to configure it on first run. This makes a volume optional and is beneficial for cloud approaches where filesystem manipulation isn't as easy.

Most of the `sed` code for editing the config is copy paste-able. There's one pattern for a digit value, and one for a string value. It should be easy to maintain in case another config variable gets added in the future.

**Comment by Code-You-Fools** [comment]
If you're going to use `--no-cache`, there's no need to run `apk update` - all it will do is make the container larger. I'd also recommend adding `-U` to your flags just to have the system as up-to-date as possible.

**Comment by Code-You-Fools** [comment]
Modified your Dockerfile to eliminate unnecessary `apk update` calls (which would just needlessly bloat the image as you're using `--no-cache` as you should be) and to pull the latest released version of the source code.

```FROM alpine:edge as base

RUN apk -U --no-cache add \
        libgomp \
        libcurl

WORKDIR /app

FROM base AS builder

RUN apk -U --no-cache add \
        gcc \
        make \
        musl-dev \
        curl-dev \
        libconfig-dev \
        curl \
        jq

RUN curl -fsSL $(curl https://api.github.com/repos/SevenChords/CipesAtHome/releases/latest | jq -r .tarball_url) | tar -xz --strip 1

RUN make

FROM base

RUN apk -U --no-cache add \
        libcurl \
        libconfig \
        sed

COPY --from=builder /app/recipesAtHome /app/config.txt /app/

COPY entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN ln -s /usr/local/bin/docker-entrypoint.sh /

VOLUME [ "/config" ]

ENTRYPOINT [ "docker-entrypoint.sh" ]```

**Comment by ann4belle** [comment]
The only problem I can see in this is the `apk update` calls - they're unnecessary since you're using `--no-cache` (which you should be in a container image) and only serve to add bloat.

**Comment by claabs** [comment]
TIL! Thanks for the advice. That cuts the image from 7.41 MB to 3.81 MB. 

BTW this is ready to merge, unless you plan on adding any new non-dev config options soon (like with #18), in which case I'll have to add them to the `entrypoint.sh` script as environment variables.

**Comment by malleoz** [comment]
Merged. I will have SevenChords create the Docker Hub page soon. Thanks!

**Pull request merged**
